import 'economy.dart';
class PremiumGiftCatalog {
  static const normal = <GiftDefinition>[
    GiftDefinition(id: "rose", name: "Rose", price: 100, effectKind: 'scene', emoji: "🌹"),
    GiftDefinition(id: "crystal", name: "Crystal", price: 500, effectKind: 'scene', emoji: "💎"),
    GiftDefinition(id: "crown", name: "Crown", price: 1000, effectKind: 'scene', emoji: "👑"),
    GiftDefinition(id: "hot-biryani", name: "Royal Biryani", price: 50000, effectKind: 'scene', emoji: "🍲"),
    GiftDefinition(id: "rose-bouquet", name: "Rose Bouquet", price: 150000, effectKind: 'scene', emoji: "💐"),
    GiftDefinition(id: "steaming-dim-sum", name: "Steaming Dim Sum", price: 168000, effectKind: 'scene', emoji: "🥟"),
    GiftDefinition(id: "royal-saffron-feast", name: "Royal Saffron Feast", price: 208000, effectKind: 'scene', emoji: "🍛"),
    GiftDefinition(id: "chocolate-fountain", name: "Chocolate Fountain", price: 263000, effectKind: 'scene', emoji: "🍫"),
    GiftDefinition(id: "sushi-palace", name: "Sushi Palace", price: 332000, effectKind: 'scene', emoji: "🍣"),
    GiftDefinition(id: "royal-cake", name: "Royal Cake", price: 412000, effectKind: 'scene', emoji: "🎂"),
    GiftDefinition(id: "golden-dragon", name: "Golden Dragon", price: 504000, effectKind: 'scene', emoji: "🐉"),
    GiftDefinition(id: "phoenix", name: "Phoenix", price: 607000, effectKind: 'scene', emoji: "🦅"),
    GiftDefinition(id: "diamond-crown", name: "Diamond Crown", price: 720000, effectKind: 'scene', emoji: "👑"),
    GiftDefinition(id: "emerald-ring", name: "Emerald Ring", price: 842000, effectKind: 'scene', emoji: "💍"),
    GiftDefinition(id: "crystal-swan", name: "Crystal Swan", price: 973000, effectKind: 'scene', emoji: "🦢"),
    GiftDefinition(id: "royal-carriage", name: "Royal Carriage", price: 1114000, effectKind: 'scene', emoji: "🎠"),
    GiftDefinition(id: "diamond-yacht", name: "Diamond Yacht", price: 1262000, effectKind: 'scene', emoji: "🛥️"),
    GiftDefinition(id: "luxury-jet", name: "Luxury Jet", price: 1420000, effectKind: 'scene', emoji: "✈️"),
    GiftDefinition(id: "star-castle", name: "Star Castle", price: 1585000, effectKind: 'scene', emoji: "🏰"),
    GiftDefinition(id: "moon-palace", name: "Moon Palace", price: 1758000, effectKind: 'scene', emoji: "🌙"),
    GiftDefinition(id: "rainbow-waterfall", name: "Rainbow Waterfall", price: 1938000, effectKind: 'scene', emoji: "🌊"),
    GiftDefinition(id: "golden-peacock", name: "Golden Peacock", price: 2126000, effectKind: 'scene', emoji: "🦚"),
    GiftDefinition(id: "aurora", name: "Aurora", price: 2322000, effectKind: 'scene', emoji: "🌌"),
    GiftDefinition(id: "galaxy-garden", name: "Galaxy Garden", price: 2525000, effectKind: 'scene', emoji: "🌷"),
    GiftDefinition(id: "enchanted-forest", name: "Enchanted Forest", price: 2734000, effectKind: 'scene', emoji: "🌳"),
    GiftDefinition(id: "ocean-pearl", name: "Ocean Pearl", price: 2951000, effectKind: 'scene', emoji: "🦪"),
    GiftDefinition(id: "magic-butterfly", name: "Magic Butterfly", price: 3174000, effectKind: 'scene', emoji: "🦋"),
    GiftDefinition(id: "royal-tiger", name: "Royal Tiger", price: 3405000, effectKind: 'scene', emoji: "🐯"),
    GiftDefinition(id: "snow-leopard", name: "Snow Leopard", price: 3641000, effectKind: 'scene', emoji: "🐆"),
    GiftDefinition(id: "golden-lion", name: "Golden Lion", price: 3885000, effectKind: 'scene', emoji: "🦁"),
    GiftDefinition(id: "fire-dragon", name: "Fire Dragon", price: 4134000, effectKind: 'scene', emoji: "🐲"),
    GiftDefinition(id: "ice-dragon", name: "Ice Dragon", price: 4390000, effectKind: 'scene', emoji: "🐉"),
    GiftDefinition(id: "celestial-horse", name: "Celestial Horse", price: 4652000, effectKind: 'scene', emoji: "🐎"),
    GiftDefinition(id: "diamond-fountain", name: "Diamond Fountain", price: 4921000, effectKind: 'scene', emoji: "⛲"),
    GiftDefinition(id: "royal-opera", name: "Royal Opera", price: 5195000, effectKind: 'scene', emoji: "🎭"),
    GiftDefinition(id: "sky-lanterns", name: "Sky Lanterns", price: 5476000, effectKind: 'scene', emoji: "🏮"),
    GiftDefinition(id: "meteor-shower", name: "Meteor Shower", price: 5762000, effectKind: 'scene', emoji: "☄️"),
    GiftDefinition(id: "golden-temple", name: "Golden Temple", price: 6055000, effectKind: 'scene', emoji: "🛕"),
    GiftDefinition(id: "rainbow-castle", name: "Rainbow Castle", price: 6353000, effectKind: 'scene', emoji: "🏰"),
    GiftDefinition(id: "cloud-kingdom", name: "Cloud Kingdom", price: 6657000, effectKind: 'scene', emoji: "☁️"),
    GiftDefinition(id: "space-shuttle", name: "Space Shuttle", price: 6966000, effectKind: 'scene', emoji: "🚀"),
    GiftDefinition(id: "royal-ferrari", name: "Royal Ferrari", price: 7281000, effectKind: 'scene', emoji: "🏎️"),
    GiftDefinition(id: "crystal-palace", name: "Crystal Palace", price: 7602000, effectKind: 'scene', emoji: "🏛️"),
    GiftDefinition(id: "galaxy-whale", name: "Galaxy Whale", price: 7928000, effectKind: 'scene', emoji: "🐋"),
    GiftDefinition(id: "solar-crown", name: "Solar Crown", price: 8260000, effectKind: 'scene', emoji: "☀️"),
    GiftDefinition(id: "infinity-rose", name: "Infinity Rose", price: 8598000, effectKind: 'scene', emoji: "🌹"),
    GiftDefinition(id: "diamond-universe", name: "Diamond Universe", price: 8940000, effectKind: 'scene', emoji: "💎"),
    GiftDefinition(id: "phoenix-kingdom", name: "Phoenix Kingdom", price: 9288000, effectKind: 'scene', emoji: "🦅"),
    GiftDefinition(id: "dragon-empire", name: "Dragon Empire", price: 9641000, effectKind: 'scene', emoji: "🐲"),
    GiftDefinition(id: "ultimate-galaxy", name: "Ultimate Galaxy", price: 10000000, effectKind: 'scene', emoji: "🌌"),
  ];
  static const cp = <GiftDefinition>[
    GiftDefinition(id: "cp-heart", name: "My Heart", price: 44444, effectKind: 'scene', emoji: "💗"),
    GiftDefinition(id: "cp-invite", name: "CP Invite", price: 2222222, effectKind: 'scene', emoji: "💌"),
    GiftDefinition(id: "cp-love-ring", name: "Love Ring", price: 150000, effectKind: 'scene', emoji: "💍"),
    GiftDefinition(id: "cp-first-kiss", name: "First Kiss", price: 500000, effectKind: 'scene', emoji: "💏"),
    GiftDefinition(id: "cp-royal-wedding", name: "Royal Wedding", price: 850000, effectKind: 'scene', emoji: "💒"),
    GiftDefinition(id: "cp-hand-in-hand", name: "Hand In Hand", price: 1200000, effectKind: 'scene', emoji: "💖"),
    GiftDefinition(id: "cp-forever-hug", name: "Forever Hug", price: 1550000, effectKind: 'scene', emoji: "💖"),
    GiftDefinition(id: "cp-moonlight-date", name: "Moonlight Date", price: 1900000, effectKind: 'scene', emoji: "💖"),
    GiftDefinition(id: "cp-rose-proposal", name: "Rose Proposal", price: 2250000, effectKind: 'scene', emoji: "💖"),
    GiftDefinition(id: "cp-heart-fountain", name: "Heart Fountain", price: 2600000, effectKind: 'scene', emoji: "💖"),
    GiftDefinition(id: "cp-love-carriage", name: "Love Carriage", price: 2950000, effectKind: 'scene', emoji: "💖"),
    GiftDefinition(id: "cp-diamond-promise", name: "Diamond Promise", price: 3300000, effectKind: 'scene', emoji: "💍"),
    GiftDefinition(id: "cp-garden-romance", name: "Garden Romance", price: 3650000, effectKind: 'scene', emoji: "💖"),
    GiftDefinition(id: "cp-beach-wedding", name: "Beach Wedding", price: 4000000, effectKind: 'scene', emoji: "💒"),
    GiftDefinition(id: "cp-valentine-palace", name: "Valentine Palace", price: 4350000, effectKind: 'scene', emoji: "💖"),
    GiftDefinition(id: "cp-twin-hearts", name: "Twin Hearts", price: 4700000, effectKind: 'scene', emoji: "💖"),
    GiftDefinition(id: "cp-anniversary-cake", name: "Anniversary Cake", price: 5050000, effectKind: 'scene', emoji: "💖"),
    GiftDefinition(id: "cp-starlight-couple", name: "Starlight Couple", price: 5400000, effectKind: 'scene', emoji: "💖"),
    GiftDefinition(id: "cp-eternal-vows", name: "Eternal Vows", price: 5750000, effectKind: 'scene', emoji: "💒"),
    GiftDefinition(id: "cp-infinity-love", name: "Infinity Love", price: 6100000, effectKind: 'scene', emoji: "💖"),
  ];
  static const enemy = <GiftDefinition>[
    GiftDefinition(id: "enemy-mark", name: "Enemy Mark", price: 44444, effectKind: 'scene', emoji: "⚠️"),
    GiftDefinition(id: "enemy-dark-crown", name: "Dark Crown", price: 150000, effectKind: 'scene', emoji: "♛"),
    GiftDefinition(id: "enemy-poison-dagger", name: "Poison Dagger", price: 500000, effectKind: 'scene', emoji: "🗡️"),
    GiftDefinition(id: "enemy-red-skull-flame", name: "Red Skull Flame", price: 850000, effectKind: 'scene', emoji: "💀"),
    GiftDefinition(id: "enemy-black-storm", name: "Black Storm", price: 1200000, effectKind: 'scene', emoji: "🌩️"),
    GiftDefinition(id: "enemy-hell-chain", name: "Hell Chain", price: 1550000, effectKind: 'scene', emoji: "⛓️"),
    GiftDefinition(id: "enemy-rage-bomb", name: "Rage Bomb", price: 1900000, effectKind: 'scene', emoji: "💥"),
    GiftDefinition(id: "enemy-demon-eye", name: "Demon Eye", price: 2250000, effectKind: 'scene', emoji: "👁️"),
    GiftDefinition(id: "enemy-final-warning", name: "Final Warning", price: 2600000, effectKind: 'scene', emoji: "☠️"),
    GiftDefinition(id: "enemy-hunter-blade", name: "Hunter Blade", price: 2950000, effectKind: 'scene', emoji: "⚔️"),
    GiftDefinition(id: "enemy-shadow-coffin", name: "Shadow Coffin", price: 3300000, effectKind: 'scene', emoji: "⚰️"),
    GiftDefinition(id: "enemy-crimson-reaper", name: "Crimson Reaper", price: 3650000, effectKind: 'scene', emoji: "🔱"),
    GiftDefinition(id: "enemy-war-throne", name: "War Throne", price: 4000000, effectKind: 'scene', emoji: "🪑"),
    GiftDefinition(id: "enemy-execution-order", name: "Execution Order", price: 4350000, effectKind: 'scene', emoji: "📜"),
    GiftDefinition(id: "enemy-abyss-king", name: "Abyss King", price: 4700000, effectKind: 'scene', emoji: "👹"),
  ];
  static const countries = <GiftDefinition>[
    GiftDefinition(id: "flag-ad", name: "AD • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇦🇩"),
    GiftDefinition(id: "flag-ae", name: "UAE • Burj Khalifa", price: 150000, effectKind: 'scene', emoji: "🇦🇪"),
    GiftDefinition(id: "flag-af", name: "AF • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇦🇫"),
    GiftDefinition(id: "flag-ag", name: "AG • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇦🇬"),
    GiftDefinition(id: "flag-ai", name: "AI • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇦🇮"),
    GiftDefinition(id: "flag-al", name: "AL • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇦🇱"),
    GiftDefinition(id: "flag-am", name: "AM • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇦🇲"),
    GiftDefinition(id: "flag-ao", name: "AO • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇦🇴"),
    GiftDefinition(id: "flag-aq", name: "AQ • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇦🇶"),
    GiftDefinition(id: "flag-ar", name: "AR • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇦🇷"),
    GiftDefinition(id: "flag-as", name: "AS • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇦🇸"),
    GiftDefinition(id: "flag-at", name: "AT • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇦🇹"),
    GiftDefinition(id: "flag-au", name: "Australia • Opera House", price: 150000, effectKind: 'scene', emoji: "🇦🇺"),
    GiftDefinition(id: "flag-aw", name: "AW • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇦🇼"),
    GiftDefinition(id: "flag-ax", name: "AX • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇦🇽"),
    GiftDefinition(id: "flag-az", name: "AZ • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇦🇿"),
    GiftDefinition(id: "flag-ba", name: "BA • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇧🇦"),
    GiftDefinition(id: "flag-bb", name: "BB • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇧🇧"),
    GiftDefinition(id: "flag-bd", name: "Bangladesh • National Monument", price: 150000, effectKind: 'scene', emoji: "🇧🇩"),
    GiftDefinition(id: "flag-be", name: "BE • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇧🇪"),
    GiftDefinition(id: "flag-bf", name: "BF • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇧🇫"),
    GiftDefinition(id: "flag-bg", name: "BG • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇧🇬"),
    GiftDefinition(id: "flag-bh", name: "BH • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇧🇭"),
    GiftDefinition(id: "flag-bi", name: "BI • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇧🇮"),
    GiftDefinition(id: "flag-bj", name: "BJ • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇧🇯"),
    GiftDefinition(id: "flag-bl", name: "BL • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇧🇱"),
    GiftDefinition(id: "flag-bm", name: "BM • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇧🇲"),
    GiftDefinition(id: "flag-bn", name: "BN • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇧🇳"),
    GiftDefinition(id: "flag-bo", name: "BO • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇧🇴"),
    GiftDefinition(id: "flag-bq", name: "BQ • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇧🇶"),
    GiftDefinition(id: "flag-br", name: "Brazil • Carnival", price: 150000, effectKind: 'scene', emoji: "🇧🇷"),
    GiftDefinition(id: "flag-bs", name: "BS • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇧🇸"),
    GiftDefinition(id: "flag-bt", name: "BT • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇧🇹"),
    GiftDefinition(id: "flag-bv", name: "BV • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇧🇻"),
    GiftDefinition(id: "flag-bw", name: "BW • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇧🇼"),
    GiftDefinition(id: "flag-by", name: "BY • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇧🇾"),
    GiftDefinition(id: "flag-bz", name: "BZ • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇧🇿"),
    GiftDefinition(id: "flag-ca", name: "Canada • Maple Falls", price: 150000, effectKind: 'scene', emoji: "🇨🇦"),
    GiftDefinition(id: "flag-cc", name: "CC • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇨🇨"),
    GiftDefinition(id: "flag-cd", name: "CD • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇨🇩"),
    GiftDefinition(id: "flag-cf", name: "CF • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇨🇫"),
    GiftDefinition(id: "flag-cg", name: "CG • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇨🇬"),
    GiftDefinition(id: "flag-ch", name: "CH • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇨🇭"),
    GiftDefinition(id: "flag-ci", name: "CI • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇨🇮"),
    GiftDefinition(id: "flag-ck", name: "CK • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇨🇰"),
    GiftDefinition(id: "flag-cl", name: "CL • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇨🇱"),
    GiftDefinition(id: "flag-cm", name: "CM • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇨🇲"),
    GiftDefinition(id: "flag-cn", name: "China • Great Wall", price: 150000, effectKind: 'scene', emoji: "🇨🇳"),
    GiftDefinition(id: "flag-co", name: "CO • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇨🇴"),
    GiftDefinition(id: "flag-cr", name: "CR • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇨🇷"),
    GiftDefinition(id: "flag-cu", name: "CU • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇨🇺"),
    GiftDefinition(id: "flag-cv", name: "CV • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇨🇻"),
    GiftDefinition(id: "flag-cw", name: "CW • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇨🇼"),
    GiftDefinition(id: "flag-cx", name: "CX • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇨🇽"),
    GiftDefinition(id: "flag-cy", name: "CY • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇨🇾"),
    GiftDefinition(id: "flag-cz", name: "CZ • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇨🇿"),
    GiftDefinition(id: "flag-de", name: "DE • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇩🇪"),
    GiftDefinition(id: "flag-dj", name: "DJ • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇩🇯"),
    GiftDefinition(id: "flag-dk", name: "DK • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇩🇰"),
    GiftDefinition(id: "flag-dm", name: "DM • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇩🇲"),
    GiftDefinition(id: "flag-do", name: "DO • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇩🇴"),
    GiftDefinition(id: "flag-dz", name: "DZ • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇩🇿"),
    GiftDefinition(id: "flag-ec", name: "EC • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇪🇨"),
    GiftDefinition(id: "flag-ee", name: "EE • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇪🇪"),
    GiftDefinition(id: "flag-eg", name: "Egypt • Pyramids", price: 150000, effectKind: 'scene', emoji: "🇪🇬"),
    GiftDefinition(id: "flag-eh", name: "EH • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇪🇭"),
    GiftDefinition(id: "flag-er", name: "ER • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇪🇷"),
    GiftDefinition(id: "flag-es", name: "ES • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇪🇸"),
    GiftDefinition(id: "flag-et", name: "ET • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇪🇹"),
    GiftDefinition(id: "flag-fi", name: "FI • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇫🇮"),
    GiftDefinition(id: "flag-fj", name: "FJ • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇫🇯"),
    GiftDefinition(id: "flag-fk", name: "FK • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇫🇰"),
    GiftDefinition(id: "flag-fm", name: "FM • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇫🇲"),
    GiftDefinition(id: "flag-fo", name: "FO • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇫🇴"),
    GiftDefinition(id: "flag-fr", name: "France • Eiffel Tower", price: 150000, effectKind: 'scene', emoji: "🇫🇷"),
    GiftDefinition(id: "flag-ga", name: "GA • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇬🇦"),
    GiftDefinition(id: "flag-gb", name: "United Kingdom • Big Ben", price: 150000, effectKind: 'scene', emoji: "🇬🇧"),
    GiftDefinition(id: "flag-gd", name: "GD • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇬🇩"),
    GiftDefinition(id: "flag-ge", name: "GE • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇬🇪"),
    GiftDefinition(id: "flag-gf", name: "GF • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇬🇫"),
    GiftDefinition(id: "flag-gg", name: "GG • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇬🇬"),
    GiftDefinition(id: "flag-gh", name: "GH • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇬🇭"),
    GiftDefinition(id: "flag-gi", name: "GI • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇬🇮"),
    GiftDefinition(id: "flag-gl", name: "GL • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇬🇱"),
    GiftDefinition(id: "flag-gm", name: "GM • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇬🇲"),
    GiftDefinition(id: "flag-gn", name: "GN • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇬🇳"),
    GiftDefinition(id: "flag-gp", name: "GP • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇬🇵"),
    GiftDefinition(id: "flag-gq", name: "GQ • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇬🇶"),
    GiftDefinition(id: "flag-gr", name: "GR • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇬🇷"),
    GiftDefinition(id: "flag-gs", name: "GS • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇬🇸"),
    GiftDefinition(id: "flag-gt", name: "GT • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇬🇹"),
    GiftDefinition(id: "flag-gu", name: "GU • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇬🇺"),
    GiftDefinition(id: "flag-gw", name: "GW • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇬🇼"),
    GiftDefinition(id: "flag-gy", name: "GY • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇬🇾"),
    GiftDefinition(id: "flag-hk", name: "HK • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇭🇰"),
    GiftDefinition(id: "flag-hm", name: "HM • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇭🇲"),
    GiftDefinition(id: "flag-hn", name: "HN • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇭🇳"),
    GiftDefinition(id: "flag-hr", name: "HR • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇭🇷"),
    GiftDefinition(id: "flag-ht", name: "HT • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇭🇹"),
    GiftDefinition(id: "flag-hu", name: "HU • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇭🇺"),
    GiftDefinition(id: "flag-id", name: "ID • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇮🇩"),
    GiftDefinition(id: "flag-ie", name: "IE • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇮🇪"),
    GiftDefinition(id: "flag-il", name: "IL • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇮🇱"),
    GiftDefinition(id: "flag-im", name: "IM • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇮🇲"),
    GiftDefinition(id: "flag-in", name: "India • Taj Mahal", price: 150000, effectKind: 'scene', emoji: "🇮🇳"),
    GiftDefinition(id: "flag-io", name: "IO • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇮🇴"),
    GiftDefinition(id: "flag-iq", name: "IQ • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇮🇶"),
    GiftDefinition(id: "flag-ir", name: "IR • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇮🇷"),
    GiftDefinition(id: "flag-is", name: "IS • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇮🇸"),
    GiftDefinition(id: "flag-it", name: "Italy • Colosseum", price: 150000, effectKind: 'scene', emoji: "🇮🇹"),
    GiftDefinition(id: "flag-je", name: "JE • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇯🇪"),
    GiftDefinition(id: "flag-jm", name: "JM • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇯🇲"),
    GiftDefinition(id: "flag-jo", name: "JO • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇯🇴"),
    GiftDefinition(id: "flag-jp", name: "Japan • Mount Fuji", price: 150000, effectKind: 'scene', emoji: "🇯🇵"),
    GiftDefinition(id: "flag-ke", name: "KE • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇰🇪"),
    GiftDefinition(id: "flag-kg", name: "KG • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇰🇬"),
    GiftDefinition(id: "flag-kh", name: "KH • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇰🇭"),
    GiftDefinition(id: "flag-ki", name: "KI • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇰🇮"),
    GiftDefinition(id: "flag-km", name: "KM • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇰🇲"),
    GiftDefinition(id: "flag-kn", name: "KN • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇰🇳"),
    GiftDefinition(id: "flag-kp", name: "KP • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇰🇵"),
    GiftDefinition(id: "flag-kr", name: "South Korea • Seoul Palace", price: 150000, effectKind: 'scene', emoji: "🇰🇷"),
    GiftDefinition(id: "flag-kw", name: "KW • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇰🇼"),
    GiftDefinition(id: "flag-ky", name: "KY • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇰🇾"),
    GiftDefinition(id: "flag-kz", name: "KZ • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇰🇿"),
    GiftDefinition(id: "flag-la", name: "LA • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇱🇦"),
    GiftDefinition(id: "flag-lb", name: "LB • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇱🇧"),
    GiftDefinition(id: "flag-lc", name: "LC • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇱🇨"),
    GiftDefinition(id: "flag-li", name: "LI • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇱🇮"),
    GiftDefinition(id: "flag-lk", name: "LK • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇱🇰"),
    GiftDefinition(id: "flag-lr", name: "LR • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇱🇷"),
    GiftDefinition(id: "flag-ls", name: "LS • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇱🇸"),
    GiftDefinition(id: "flag-lt", name: "LT • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇱🇹"),
    GiftDefinition(id: "flag-lu", name: "LU • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇱🇺"),
    GiftDefinition(id: "flag-lv", name: "LV • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇱🇻"),
    GiftDefinition(id: "flag-ly", name: "LY • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇱🇾"),
    GiftDefinition(id: "flag-ma", name: "MA • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇦"),
    GiftDefinition(id: "flag-mc", name: "MC • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇨"),
    GiftDefinition(id: "flag-md", name: "MD • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇩"),
    GiftDefinition(id: "flag-me", name: "ME • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇪"),
    GiftDefinition(id: "flag-mf", name: "MF • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇫"),
    GiftDefinition(id: "flag-mg", name: "MG • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇬"),
    GiftDefinition(id: "flag-mh", name: "MH • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇭"),
    GiftDefinition(id: "flag-mk", name: "MK • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇰"),
    GiftDefinition(id: "flag-ml", name: "ML • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇱"),
    GiftDefinition(id: "flag-mm", name: "MM • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇲"),
    GiftDefinition(id: "flag-mn", name: "MN • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇳"),
    GiftDefinition(id: "flag-mo", name: "MO • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇴"),
    GiftDefinition(id: "flag-mp", name: "MP • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇵"),
    GiftDefinition(id: "flag-mq", name: "MQ • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇶"),
    GiftDefinition(id: "flag-mr", name: "MR • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇷"),
    GiftDefinition(id: "flag-ms", name: "MS • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇸"),
    GiftDefinition(id: "flag-mt", name: "MT • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇹"),
    GiftDefinition(id: "flag-mu", name: "MU • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇺"),
    GiftDefinition(id: "flag-mv", name: "MV • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇻"),
    GiftDefinition(id: "flag-mw", name: "MW • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇼"),
    GiftDefinition(id: "flag-mx", name: "MX • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇽"),
    GiftDefinition(id: "flag-my", name: "MY • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇾"),
    GiftDefinition(id: "flag-mz", name: "MZ • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇲🇿"),
    GiftDefinition(id: "flag-na", name: "NA • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇳🇦"),
    GiftDefinition(id: "flag-nc", name: "NC • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇳🇨"),
    GiftDefinition(id: "flag-ne", name: "NE • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇳🇪"),
    GiftDefinition(id: "flag-nf", name: "NF • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇳🇫"),
    GiftDefinition(id: "flag-ng", name: "NG • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇳🇬"),
    GiftDefinition(id: "flag-ni", name: "NI • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇳🇮"),
    GiftDefinition(id: "flag-nl", name: "NL • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇳🇱"),
    GiftDefinition(id: "flag-no", name: "NO • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇳🇴"),
    GiftDefinition(id: "flag-np", name: "Nepal • Everest", price: 150000, effectKind: 'scene', emoji: "🇳🇵"),
    GiftDefinition(id: "flag-nr", name: "NR • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇳🇷"),
    GiftDefinition(id: "flag-nu", name: "NU • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇳🇺"),
    GiftDefinition(id: "flag-nz", name: "NZ • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇳🇿"),
    GiftDefinition(id: "flag-om", name: "OM • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇴🇲"),
    GiftDefinition(id: "flag-pa", name: "PA • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇵🇦"),
    GiftDefinition(id: "flag-pe", name: "PE • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇵🇪"),
    GiftDefinition(id: "flag-pf", name: "PF • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇵🇫"),
    GiftDefinition(id: "flag-pg", name: "PG • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇵🇬"),
    GiftDefinition(id: "flag-ph", name: "PH • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇵🇭"),
    GiftDefinition(id: "flag-pk", name: "Pakistan • Badshahi Mosque", price: 150000, effectKind: 'scene', emoji: "🇵🇰"),
    GiftDefinition(id: "flag-pl", name: "PL • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇵🇱"),
    GiftDefinition(id: "flag-pm", name: "PM • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇵🇲"),
    GiftDefinition(id: "flag-pn", name: "PN • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇵🇳"),
    GiftDefinition(id: "flag-pr", name: "PR • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇵🇷"),
    GiftDefinition(id: "flag-ps", name: "PS • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇵🇸"),
    GiftDefinition(id: "flag-pt", name: "PT • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇵🇹"),
    GiftDefinition(id: "flag-pw", name: "PW • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇵🇼"),
    GiftDefinition(id: "flag-py", name: "PY • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇵🇾"),
    GiftDefinition(id: "flag-qa", name: "QA • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇶🇦"),
    GiftDefinition(id: "flag-re", name: "RE • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇷🇪"),
    GiftDefinition(id: "flag-ro", name: "RO • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇷🇴"),
    GiftDefinition(id: "flag-rs", name: "RS • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇷🇸"),
    GiftDefinition(id: "flag-ru", name: "Russia • Saint Basil", price: 150000, effectKind: 'scene', emoji: "🇷🇺"),
    GiftDefinition(id: "flag-rw", name: "RW • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇷🇼"),
    GiftDefinition(id: "flag-sa", name: "Saudi Arabia • Desert Palace", price: 150000, effectKind: 'scene', emoji: "🇸🇦"),
    GiftDefinition(id: "flag-sb", name: "SB • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇸🇧"),
    GiftDefinition(id: "flag-sc", name: "SC • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇸🇨"),
    GiftDefinition(id: "flag-sd", name: "SD • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇸🇩"),
    GiftDefinition(id: "flag-se", name: "SE • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇸🇪"),
    GiftDefinition(id: "flag-sg", name: "SG • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇸🇬"),
    GiftDefinition(id: "flag-sh", name: "SH • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇸🇭"),
    GiftDefinition(id: "flag-si", name: "SI • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇸🇮"),
    GiftDefinition(id: "flag-sj", name: "SJ • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇸🇯"),
    GiftDefinition(id: "flag-sk", name: "SK • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇸🇰"),
    GiftDefinition(id: "flag-sl", name: "SL • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇸🇱"),
    GiftDefinition(id: "flag-sm", name: "SM • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇸🇲"),
    GiftDefinition(id: "flag-sn", name: "SN • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇸🇳"),
    GiftDefinition(id: "flag-so", name: "SO • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇸🇴"),
    GiftDefinition(id: "flag-sr", name: "SR • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇸🇷"),
    GiftDefinition(id: "flag-ss", name: "SS • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇸🇸"),
    GiftDefinition(id: "flag-st", name: "ST • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇸🇹"),
    GiftDefinition(id: "flag-sv", name: "SV • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇸🇻"),
    GiftDefinition(id: "flag-sx", name: "SX • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇸🇽"),
    GiftDefinition(id: "flag-sy", name: "SY • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇸🇾"),
    GiftDefinition(id: "flag-sz", name: "SZ • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇸🇿"),
    GiftDefinition(id: "flag-tc", name: "TC • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇹🇨"),
    GiftDefinition(id: "flag-td", name: "TD • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇹🇩"),
    GiftDefinition(id: "flag-tf", name: "TF • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇹🇫"),
    GiftDefinition(id: "flag-tg", name: "TG • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇹🇬"),
    GiftDefinition(id: "flag-th", name: "TH • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇹🇭"),
    GiftDefinition(id: "flag-tj", name: "TJ • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇹🇯"),
    GiftDefinition(id: "flag-tk", name: "TK • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇹🇰"),
    GiftDefinition(id: "flag-tl", name: "TL • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇹🇱"),
    GiftDefinition(id: "flag-tm", name: "TM • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇹🇲"),
    GiftDefinition(id: "flag-tn", name: "TN • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇹🇳"),
    GiftDefinition(id: "flag-to", name: "TO • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇹🇴"),
    GiftDefinition(id: "flag-tr", name: "Türkiye • Cappadocia", price: 150000, effectKind: 'scene', emoji: "🇹🇷"),
    GiftDefinition(id: "flag-tt", name: "TT • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇹🇹"),
    GiftDefinition(id: "flag-tv", name: "TV • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇹🇻"),
    GiftDefinition(id: "flag-tw", name: "TW • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇹🇼"),
    GiftDefinition(id: "flag-tz", name: "TZ • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇹🇿"),
    GiftDefinition(id: "flag-ua", name: "UA • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇺🇦"),
    GiftDefinition(id: "flag-ug", name: "UG • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇺🇬"),
    GiftDefinition(id: "flag-um", name: "UM • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇺🇲"),
    GiftDefinition(id: "flag-us", name: "United States • Liberty", price: 150000, effectKind: 'scene', emoji: "🇺🇸"),
    GiftDefinition(id: "flag-uy", name: "UY • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇺🇾"),
    GiftDefinition(id: "flag-uz", name: "UZ • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇺🇿"),
    GiftDefinition(id: "flag-va", name: "VA • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇻🇦"),
    GiftDefinition(id: "flag-vc", name: "VC • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇻🇨"),
    GiftDefinition(id: "flag-ve", name: "VE • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇻🇪"),
    GiftDefinition(id: "flag-vg", name: "VG • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇻🇬"),
    GiftDefinition(id: "flag-vi", name: "VI • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇻🇮"),
    GiftDefinition(id: "flag-vn", name: "VN • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇻🇳"),
    GiftDefinition(id: "flag-vu", name: "VU • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇻🇺"),
    GiftDefinition(id: "flag-wf", name: "WF • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇼🇫"),
    GiftDefinition(id: "flag-ws", name: "WS • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇼🇸"),
    GiftDefinition(id: "flag-ye", name: "YE • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇾🇪"),
    GiftDefinition(id: "flag-yt", name: "YT • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇾🇹"),
    GiftDefinition(id: "flag-za", name: "South Africa • Table Mountain", price: 150000, effectKind: 'scene', emoji: "🇿🇦"),
    GiftDefinition(id: "flag-zm", name: "ZM • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇿🇲"),
    GiftDefinition(id: "flag-zw", name: "ZW • National Celebration", price: 150000, effectKind: 'scene', emoji: "🇿🇼"),
  ];
  static const scenes = <String,String>{
"rose": "rose",
"crystal": "jewel",
"crown": "jewel",
"hot-biryani": "food",
"rose-bouquet": "rose",
"steaming-dim-sum": "food",
"royal-saffron-feast": "food",
"chocolate-fountain": "food",
"sushi-palace": "food",
"royal-cake": "food",
"golden-dragon": "dragon",
"phoenix": "dragon",
"diamond-crown": "spectacle",
"emerald-ring": "spectacle",
"crystal-swan": "spectacle",
"royal-carriage": "spectacle",
"diamond-yacht": "spectacle",
"luxury-jet": "spectacle",
"star-castle": "spectacle",
"moon-palace": "spectacle",
"rainbow-waterfall": "spectacle",
"golden-peacock": "spectacle",
"aurora": "spectacle",
"galaxy-garden": "spectacle",
"enchanted-forest": "spectacle",
"ocean-pearl": "spectacle",
"magic-butterfly": "spectacle",
"royal-tiger": "spectacle",
"snow-leopard": "spectacle",
"golden-lion": "spectacle",
"fire-dragon": "dragon",
"ice-dragon": "dragon",
"celestial-horse": "spectacle",
"diamond-fountain": "spectacle",
"royal-opera": "spectacle",
"sky-lanterns": "spectacle",
"meteor-shower": "spectacle",
"golden-temple": "spectacle",
"rainbow-castle": "spectacle",
"cloud-kingdom": "spectacle",
"space-shuttle": "spectacle",
"royal-ferrari": "spectacle",
"crystal-palace": "spectacle",
"galaxy-whale": "spectacle",
"solar-crown": "spectacle",
"infinity-rose": "rose",
"diamond-universe": "spectacle",
"phoenix-kingdom": "dragon",
"dragon-empire": "dragon",
"ultimate-galaxy": "spectacle",
"cp-heart": "heart",
"cp-invite": "love",
"cp-love-ring": "love",
"cp-first-kiss": "couple",
"cp-royal-wedding": "wedding",
"cp-hand-in-hand": "couple",
"cp-forever-hug": "couple",
"cp-moonlight-date": "couple",
"cp-rose-proposal": "love",
"cp-heart-fountain": "love",
"cp-love-carriage": "love",
"cp-diamond-promise": "love",
"cp-garden-romance": "couple",
"cp-beach-wedding": "wedding",
"cp-valentine-palace": "love",
"cp-twin-hearts": "love",
"cp-anniversary-cake": "love",
"cp-starlight-couple": "couple",
"cp-eternal-vows": "wedding",
"cp-infinity-love": "love",
"flag-ad": "flag",
"flag-ae": "flag",
"flag-af": "flag",
"flag-ag": "flag",
"flag-ai": "flag",
"flag-al": "flag",
"flag-am": "flag",
"flag-ao": "flag",
"flag-aq": "flag",
"flag-ar": "flag",
"flag-as": "flag",
"flag-at": "flag",
"flag-au": "flag",
"flag-aw": "flag",
"flag-ax": "flag",
"flag-az": "flag",
"flag-ba": "flag",
"flag-bb": "flag",
"flag-bd": "flag",
"flag-be": "flag",
"flag-bf": "flag",
"flag-bg": "flag",
"flag-bh": "flag",
"flag-bi": "flag",
"flag-bj": "flag",
"flag-bl": "flag",
"flag-bm": "flag",
"flag-bn": "flag",
"flag-bo": "flag",
"flag-bq": "flag",
"flag-br": "flag",
"flag-bs": "flag",
"flag-bt": "flag",
"flag-bv": "flag",
"flag-bw": "flag",
"flag-by": "flag",
"flag-bz": "flag",
"flag-ca": "flag",
"flag-cc": "flag",
"flag-cd": "flag",
"flag-cf": "flag",
"flag-cg": "flag",
"flag-ch": "flag",
"flag-ci": "flag",
"flag-ck": "flag",
"flag-cl": "flag",
"flag-cm": "flag",
"flag-cn": "flag",
"flag-co": "flag",
"flag-cr": "flag",
"flag-cu": "flag",
"flag-cv": "flag",
"flag-cw": "flag",
"flag-cx": "flag",
"flag-cy": "flag",
"flag-cz": "flag",
"flag-de": "flag",
"flag-dj": "flag",
"flag-dk": "flag",
"flag-dm": "flag",
"flag-do": "flag",
"flag-dz": "flag",
"flag-ec": "flag",
"flag-ee": "flag",
"flag-eg": "flag",
"flag-eh": "flag",
"flag-er": "flag",
"flag-es": "flag",
"flag-et": "flag",
"flag-fi": "flag",
"flag-fj": "flag",
"flag-fk": "flag",
"flag-fm": "flag",
"flag-fo": "flag",
"flag-fr": "flag",
"flag-ga": "flag",
"flag-gb": "flag",
"flag-gd": "flag",
"flag-ge": "flag",
"flag-gf": "flag",
"flag-gg": "flag",
"flag-gh": "flag",
"flag-gi": "flag",
"flag-gl": "flag",
"flag-gm": "flag",
"flag-gn": "flag",
"flag-gp": "flag",
"flag-gq": "flag",
"flag-gr": "flag",
"flag-gs": "flag",
"flag-gt": "flag",
"flag-gu": "flag",
"flag-gw": "flag",
"flag-gy": "flag",
"flag-hk": "flag",
"flag-hm": "flag",
"flag-hn": "flag",
"flag-hr": "flag",
"flag-ht": "flag",
"flag-hu": "flag",
"flag-id": "flag",
"flag-ie": "flag",
"flag-il": "flag",
"flag-im": "flag",
"flag-in": "flag",
"flag-io": "flag",
"flag-iq": "flag",
"flag-ir": "flag",
"flag-is": "flag",
"flag-it": "flag",
"flag-je": "flag",
"flag-jm": "flag",
"flag-jo": "flag",
"flag-jp": "flag",
"flag-ke": "flag",
"flag-kg": "flag",
"flag-kh": "flag",
"flag-ki": "flag",
"flag-km": "flag",
"flag-kn": "flag",
"flag-kp": "flag",
"flag-kr": "flag",
"flag-kw": "flag",
"flag-ky": "flag",
"flag-kz": "flag",
"flag-la": "flag",
"flag-lb": "flag",
"flag-lc": "flag",
"flag-li": "flag",
"flag-lk": "flag",
"flag-lr": "flag",
"flag-ls": "flag",
"flag-lt": "flag",
"flag-lu": "flag",
"flag-lv": "flag",
"flag-ly": "flag",
"flag-ma": "flag",
"flag-mc": "flag",
"flag-md": "flag",
"flag-me": "flag",
"flag-mf": "flag",
"flag-mg": "flag",
"flag-mh": "flag",
"flag-mk": "flag",
"flag-ml": "flag",
"flag-mm": "flag",
"flag-mn": "flag",
"flag-mo": "flag",
"flag-mp": "flag",
"flag-mq": "flag",
"flag-mr": "flag",
"flag-ms": "flag",
"flag-mt": "flag",
"flag-mu": "flag",
"flag-mv": "flag",
"flag-mw": "flag",
"flag-mx": "flag",
"flag-my": "flag",
"flag-mz": "flag",
"flag-na": "flag",
"flag-nc": "flag",
"flag-ne": "flag",
"flag-nf": "flag",
"flag-ng": "flag",
"flag-ni": "flag",
"flag-nl": "flag",
"flag-no": "flag",
"flag-np": "flag",
"flag-nr": "flag",
"flag-nu": "flag",
"flag-nz": "flag",
"flag-om": "flag",
"flag-pa": "flag",
"flag-pe": "flag",
"flag-pf": "flag",
"flag-pg": "flag",
"flag-ph": "flag",
"flag-pk": "flag",
"flag-pl": "flag",
"flag-pm": "flag",
"flag-pn": "flag",
"flag-pr": "flag",
"flag-ps": "flag",
"flag-pt": "flag",
"flag-pw": "flag",
"flag-py": "flag",
"flag-qa": "flag",
"flag-re": "flag",
"flag-ro": "flag",
"flag-rs": "flag",
"flag-ru": "flag",
"flag-rw": "flag",
"flag-sa": "flag",
"flag-sb": "flag",
"flag-sc": "flag",
"flag-sd": "flag",
"flag-se": "flag",
"flag-sg": "flag",
"flag-sh": "flag",
"flag-si": "flag",
"flag-sj": "flag",
"flag-sk": "flag",
"flag-sl": "flag",
"flag-sm": "flag",
"flag-sn": "flag",
"flag-so": "flag",
"flag-sr": "flag",
"flag-ss": "flag",
"flag-st": "flag",
"flag-sv": "flag",
"flag-sx": "flag",
"flag-sy": "flag",
"flag-sz": "flag",
"flag-tc": "flag",
"flag-td": "flag",
"flag-tf": "flag",
"flag-tg": "flag",
"flag-th": "flag",
"flag-tj": "flag",
"flag-tk": "flag",
"flag-tl": "flag",
"flag-tm": "flag",
"flag-tn": "flag",
"flag-to": "flag",
"flag-tr": "flag",
"flag-tt": "flag",
"flag-tv": "flag",
"flag-tw": "flag",
"flag-tz": "flag",
"flag-ua": "flag",
"flag-ug": "flag",
"flag-um": "flag",
"flag-us": "flag",
"flag-uy": "flag",
"flag-uz": "flag",
"flag-va": "flag",
"flag-vc": "flag",
"flag-ve": "flag",
"flag-vg": "flag",
"flag-vi": "flag",
"flag-vn": "flag",
"flag-vu": "flag",
"flag-wf": "flag",
"flag-ws": "flag",
"flag-ye": "flag",
"flag-yt": "flag",
"flag-za": "flag",
"flag-zm": "flag",
"flag-zw": "flag",
  };
  static GiftDefinition? find(String id) {
    for (final gift in [...normal,...cp,...countries]) {
      if(gift.id==id) { return gift; }
    }
    return null;
  }
  static String scene(String id)=>scenes[id]??'spectacle';
  static int holdSeconds(String id) {
    if(id.startsWith('flag-') && find(id) != null) { return 2; }
    final gift=find(id);
    if(gift==null||gift.lucky) { return 5; }
    if(gift.price>=5000000) { return 8; }
    if(gift.price>=1000000) { return 7; }
    if(gift.price>=200000) { return 6; }
    return 5;
  }
  static bool isFullScreen(String id)=>(find(id)?.price??0)>=200000;
}
