name: voice_chat_app
description: GitHub-only Flutter demo for the voice chat app project.
publish_to: 'none'
version: 0.2.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  crypto: ^3.0.6
  url_launcher: ^6.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
